port: 8080
sb_port: 8000
sb_url: http://localhost
routes:
- listen:
    url: /v2/catalog
    http_method: GET
    headers:
      "content-type":
      - "application/json"
  destination:
    url: "http://localhost:8001/catalog-service.json"
    http_method: GET
    headers:
      "content-type":
      - "application/json"
    mappings:
      services: services
    extra_fields:
      plan_updateable: true
- listen:
    url: /v2/service_instances
    http_method: PUT
    headers:
      "content-type":
      - "application/json"
  destination:
    url: "http://localhost:8001/catalog-service.json"
    http_method: GET
    headers:
      "content-type":
      - "application/json"
    mappings:
      services: services
